In [18]:
import numpy as np

# Copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
print(arr)
print("Memory location of the original array:" , id(arr))
arr[0] = 42
print(arr)
print("Memory location of the original array:" , id(arr))
print(x)


[1 2 3 4 5]
Memory location of the original array: 2460003172144
[42  2  3  4  5]
Memory location of the original array: 2460003172144
[1 2 3 4 5]


In [17]:
# View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
print(arr)
x[0] = 42
print(arr)
print(x)



[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [19]:
# check if array owns it's data
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)


None
[1 2 3 4 5]
