In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 9, 8, 7, 6, 9, 10, 9])
print(arr)
print(np.where(arr == 9))

[ 1  2  3  4  5  9  8  7  6  9 10  9]
(array([ 5,  9, 11], dtype=int64),)


In [2]:
arr = np.array([1, 2, 3, 4, 5, 9, 8, 7, 6, 9, 10, 9])
print(arr)
print(np.where(arr % 2 == 0))


[ 1  2  3  4  5  9  8  7  6  9 10  9]
(array([ 1,  3,  6,  8, 10], dtype=int64),)


In [12]:
# Search Sorted
arr = np.array([1, 2, 3, 4, 5, 9, 8, 7, 6, 9, 10, 9])
x = np.searchsorted(arr, 9)
print(x)

9


In [13]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2
