In [5]:
import numpy as np

arr = np.array([0,2,4,55,96,1,6,8,3])
print(arr)
print(np.sort(arr))

[ 0  2  4 55 96  1  6  8  3]
[ 0  1  2  3  4  6  8 55 96]


In [6]:
# alphabetically sort
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))


['apple' 'banana' 'cherry']


In [7]:
# boolean sort
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [8]:
# 2D array sort

arr = np.array([[3,2,4], [5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
