In [8]:
from numpy import random

x = random.choice([1,2,3,4,5], p=[0.1, 0.2, 0.3, 0.2, 0.2], size=(10,5))
print(x)

[[2 5 1 3 3]
 [5 1 4 3 5]
 [2 2 2 2 2]
 [3 3 2 5 3]
 [2 4 1 5 3]
 [3 5 3 5 2]
 [3 3 5 4 2]
 [1 5 2 2 2]
 [5 5 1 4 5]
 [2 5 4 2 3]]
