In [1]:
import numpy as np

print(np.__version__)


1.25.2


In [2]:
# 0-D array
a = np.array(42)
print(a)

42


In [3]:
# 1-D array
b = np.array([1, 2, 3, 4, 5])
print(b)

[1 2 3 4 5]


In [6]:
# 2-D array
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3-D array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
# check number of dimensions
print("a: ", a.ndim)
print("b: ", b.ndim)
print("c: ", c.ndim)
print("d: ", d.ndim)

a:  0
b:  1
c:  2
d:  3


In [10]:
# higher dimensions
e = np.array([1, 2, 3, 4], ndmin=5)
print(e)
print("e: ", e.ndim)

[[[[[1 2 3 4]]]]]
e:  5
