In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
print(arr[2]+arr[4])

8


In [9]:
# accessing the index of 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("2nd element on 1st dim: ", arr[0, 1])

[[1 2 3]
 [4 5 6]]
2nd element on 1st dim:  2


In [12]:
# accessing the index of 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print("Print the third element of second array of the first array: ", arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Print the third element of second array of the first array:  6


In [13]:
# Negative Indexing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print("Last element from 2nd dim: ", arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10
