In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr[1:4])

[1 2 3 4 5]
[2 3 4]


In [5]:
# 2-D array slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [6]:
# 
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
